heartbeat.monitors:

# ELK monitors
- type: http
  schedule: '*/3 * * * * *'
  urls: ["http://kibana:5601"]
  name: "monitor_kibana"
  tags: ["elk", "kibana_index", "status"]
- type: http
  schedule: '*/3 * * * * *'
  urls: ["http://elasticsearch:9200"]   
  name: "monitor_elasticsearch"
  tags: ["elk", "elasticsearch_index", "status"]

# APP monitors
- type: http
  schedule: '*/1 * * * * *'
  urls: ["http://sbrest:8080/health"]
  check.response.status: 200
  name: "monitor_app_health"
  tags: ["app_info", "health", "status"]

# USER monitors
- type: http
  schedule: '*/1 * * * * *'
  urls: ["http://sbrest:8080/api/user/"]
  check.response.status: 200
  name: "monitor_users_service_list_users"
  tags: ["app_service", "list_users", "users_service"]    
#- type: http
#  schedule: '*/1 * * * * *'
#  urls: ["http://sbrest:8080/api/user/"]
#  check.request:
#    method: POST
#    headers:
#      content-type : 'application/json'
#    body:
#      '{"name": "heartbeat", "age": "0", "salary": "0"}'
#  check.response:
#    status: 201
#  name: "monitor_users_service_post"
#  tags: ["app_service", "create_user", "users_service"]

# STACK setup
heartbeat.scheduler:
  limit: 1
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "kibana:5601"
